
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Noob
 */
public class scb extends javax.swing.JFrame {
    scbdb sdb=new scbdb();
    ResultSet IndexNum;
    /**
     * Creates new form scb
     */
    public scb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scb114 = new javax.swing.JCheckBox();
        scb115 = new javax.swing.JCheckBox();
        scb116 = new javax.swing.JCheckBox();
        scb117 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scb124 = new javax.swing.JCheckBox();
        scb125 = new javax.swing.JCheckBox();
        scb126 = new javax.swing.JCheckBox();
        scb127 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Select your Subjects");

        jLabel2.setText("SEMESTER 1");

        jLabel3.setText("SUB21(scb111) & SUB22(scb112) & SUB23(scb113) ARE COMPULSORY.");

        jLabel4.setText("You can choose up to 4 subjects from following options.");

        scb114.setText("scb114(sub24)");

        scb115.setText("scb115(sub25)");

        scb116.setText("scb116(sub33)");

        scb117.setText("scb117(sub34)");

        jLabel5.setText("SEMESTER 2");

        jLabel7.setText("SUB21(scb121) & SUB22(scb122) & SUB23(scb123) ARE COMPULSORY.");

        jLabel8.setText("You can choose up to 4 subjects from following options.");

        scb124.setText("scb124(sub29)");

        scb125.setText("scb125(sub30)");

        scb126.setText("scb126(scb39)");

        scb127.setText("scb127(scb40)");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(scb114)
                            .addComponent(scb115)
                            .addComponent(scb116)
                            .addComponent(scb117)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(scb124)
                            .addComponent(scb125)
                            .addComponent(scb126)
                            .addComponent(scb127)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(scb114)
                .addGap(18, 18, 18)
                .addComponent(scb115)
                .addGap(18, 18, 18)
                .addComponent(scb116)
                .addGap(18, 18, 18)
                .addComponent(scb117)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(scb124)
                .addGap(18, 18, 18)
                .addComponent(scb125)
                .addGap(18, 18, 18)
                .addComponent(scb126)
                .addGap(18, 18, 18)
                .addComponent(scb127)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        scbc sc=new scbc();
        int s1=0;
        int s2=0;
        if(scb114.isSelected()){sc.setScb114(1); s1++;}    else{sc.setScb114(0);}
        if(scb115.isSelected()){sc.setScb115(1); s1++;}    else{sc.setScb115(0);}
        if(scb116.isSelected()){sc.setScb116(1); s1++;}    else{sc.setScb116(0);}
        if(scb117.isSelected()){sc.setScb117(1); s1++;}    else{sc.setScb117(0);}
        if(scb124.isSelected()){sc.setScb124(1); s2++;}    else{sc.setScb124(0);}
        if(scb125.isSelected()){sc.setScb125(1); s2++;}    else{sc.setScb125(0);}
        if(scb126.isSelected()){sc.setScb126(1); s2++;}    else{sc.setScb126(0);}
        if(scb127.isSelected()){sc.setScb127(1); s2++;}    else{sc.setScb127(0);}
        
        if(s1>2 && s2>2){
            if(sdb.Enterscb(sc)){
                int op1 =0 ;
                int op2=0;
                int op3=0;
                int op4=0;
                
                String url="jdbc:mysql://localhost:3306/schoolsystem";
                String username="root";
                String password="";
                Connection con= null;
                PreparedStatement pst=null;
                
            try{    
                con=(Connection)DriverManager.getConnection(url,username,password);
                if(scb114.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"scb114");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op1=IndexNum.getInt(1);
                }
               
                  }
                if(scb115.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"scb115");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op2=IndexNum.getInt(1);
                }
               
                  }
                if(scb116.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"scb116");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op3=IndexNum.getInt(1);
                }
               
                  }
                if(scb117.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"scb117");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op4=IndexNum.getInt(1);
                }
               
                  }
            }
                  catch(Exception e){System.out.print(e);
                  }
                JOptionPane.showMessageDialog(this,"Total fee : "+(12000+(op1+op2+op3+op4))); 
            }else{
                JOptionPane.showMessageDialog(this,"failed");}
    }                                        
        else{JOptionPane.showMessageDialog(this,"you have to select more than 2");}            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox scb114;
    private javax.swing.JCheckBox scb115;
    private javax.swing.JCheckBox scb116;
    private javax.swing.JCheckBox scb117;
    private javax.swing.JCheckBox scb124;
    private javax.swing.JCheckBox scb125;
    private javax.swing.JCheckBox scb126;
    private javax.swing.JCheckBox scb127;
    // End of variables declaration//GEN-END:variables
}
