
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.IndexNum;
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Noob
 */
public class sce extends javax.swing.JFrame {
scedb sdb=new scedb();
ResultSet IndexNum;
    /**
     * Creates new form sce
     */
    public sce() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sce114 = new javax.swing.JCheckBox();
        sce115 = new javax.swing.JCheckBox();
        sce116 = new javax.swing.JCheckBox();
        sce117 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sce124 = new javax.swing.JCheckBox();
        sce125 = new javax.swing.JCheckBox();
        sce126 = new javax.swing.JCheckBox();
        sce127 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Select your Subjects");

        jLabel3.setText("SEMESTER 1");

        jLabel4.setText("SUB11(sce111) & SUB12(sce112) & SUB13(sce113) ARE COMPULSORY.");

        jLabel5.setText("You can choose up to 4 subjects from following options.");

        sce114.setText("sce114(sub14)");

        sce115.setText("sce115(sub15)");

        sce116.setText("sce116(sub35)");

        sce117.setText("sce117(sub36)");

        jLabel6.setText("SEMESTER 2");

        jLabel7.setText("SUB16(sce121) & SUB17(sce122) & SUB18(scb123) ARE COMPULSORY.");

        jLabel8.setText("You can choose up to 4 subjects from following options.");

        sce124.setText("sce124(sub19)");

        sce125.setText("sce125(sub20)");

        sce126.setText("sce126(sub41)");

        sce127.setText("sce127(sub42)");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(sce114)
                            .addComponent(sce115)
                            .addComponent(sce116)
                            .addComponent(sce117)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(sce124)
                            .addComponent(sce125)
                            .addComponent(sce126)
                            .addComponent(sce127))))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(sce114)
                .addGap(18, 18, 18)
                .addComponent(sce115)
                .addGap(18, 18, 18)
                .addComponent(sce116)
                .addGap(18, 18, 18)
                .addComponent(sce117)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(sce124)
                .addGap(18, 18, 18)
                .addComponent(sce125)
                .addGap(18, 18, 18)
                .addComponent(sce126)
                .addGap(18, 18, 18)
                .addComponent(sce127)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        scec sc=new scec();
        int s1=0;
        int s2=0;
        
        if(sce114.isSelected()){sc.setSce114(1); s1++;}    else{sc.setSce114(0);}
        if(sce115.isSelected()){sc.setSce115(1); s1++;}    else{sc.setSce115(0);}
        if(sce116.isSelected()){sc.setSce116(1); s1++;}    else{sc.setSce116(0);}
        if(sce117.isSelected()){sc.setSce117(1); s1++;}    else{sc.setSce117(0);}
        if(sce124.isSelected()){sc.setSce124(1); s2++;}    else{sc.setSce124(0);}
        if(sce125.isSelected()){sc.setSce125(1); s2++;}    else{sc.setSce125(0);}
        if(sce126.isSelected()){sc.setSce126(1); s2++;}    else{sc.setSce126(0);}
        if(sce127.isSelected()){sc.setSce127(1); s2++;}    else{sc.setSce127(0);}
        
        if(s1>2 && s2>2){
            if(sdb.Entersce(sc)){
                int op1 =0 ;
                int op2=0;
                int op3=0;
                int op4=0;
                
                String url="jdbc:mysql://localhost:3306/schoolsystem";
                String username="root";
                String password="";
                Connection con= null;
                PreparedStatement pst=null;
                
            try{    
                con=(Connection)DriverManager.getConnection(url,username,password);
                if(sce114.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"sce114");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op1=IndexNum.getInt(1);
                }
               
                  }
                if(sce115.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"sce115");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op2=IndexNum.getInt(1);
                }
               
                  }
                if(sce116.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"sce116");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op3=IndexNum.getInt(1);
                }
               
                  }
                if(sce117.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"sce117");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op4=IndexNum.getInt(1);
                }
               
                  }
            }
                  catch(Exception e){System.out.print(e);
                  }
                JOptionPane.showMessageDialog(this,"Total fee : "+(12000+(op1+op2+op3+op4))); 
            }else{
                JOptionPane.showMessageDialog(this,"failed");}
    }                                        
        else{JOptionPane.showMessageDialog(this,"you have to select more than 2");}         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox sce114;
    private javax.swing.JCheckBox sce115;
    private javax.swing.JCheckBox sce116;
    private javax.swing.JCheckBox sce117;
    private javax.swing.JCheckBox sce124;
    private javax.swing.JCheckBox sce125;
    private javax.swing.JCheckBox sce126;
    private javax.swing.JCheckBox sce127;
    // End of variables declaration//GEN-END:variables
}
