
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Noob
 */
public class scs extends javax.swing.JFrame {
    ResultSet IndexNum;
    /**
     * Creates new form scs
     */
    public scs() {
        initComponents();
    }
    scsdb sdb=new scsdb();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scs114 = new javax.swing.JCheckBox();
        scs115 = new javax.swing.JCheckBox();
        scs116 = new javax.swing.JCheckBox();
        scs117 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        scs124 = new javax.swing.JCheckBox();
        scs125 = new javax.swing.JCheckBox();
        scs126 = new javax.swing.JCheckBox();
        scs127 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Select your Subjects");

        jLabel2.setText("SEMESTER 1");

        jLabel3.setText("SUB1(scs111) & SUB2(scs112) & SUB3(scs113) ARE COMPULSORY.");

        jLabel4.setText("You can choose up to 4 subjects from following options.");

        scs114.setText("scs114(sub4)");
        scs114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scs114ActionPerformed(evt);
            }
        });

        scs115.setText("scs115(sub5)");

        scs116.setText("scs116(sub31)");

        scs117.setText("scs117(sub32)");

        jLabel5.setText("SEMESTER 2");

        jLabel6.setText("SUB6(scs121) & SUB7(scs122) & SUB8(scs123) ARE COMPULSORY.");

        jLabel7.setText("You can choose up to 4 subjects from following options.");

        scs124.setText("scs124(sub9)");

        scs125.setText("scs125(sub10)");

        scs126.setText("scs126(sub37)");

        scs127.setText("scs127(sub38)");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scs127)
                            .addComponent(scs126)
                            .addComponent(scs125)
                            .addComponent(scs124)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(scs117)
                            .addComponent(scs116)
                            .addComponent(scs115)
                            .addComponent(scs114)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addComponent(scs114, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scs115)
                .addGap(18, 18, 18)
                .addComponent(scs116)
                .addGap(18, 18, 18)
                .addComponent(scs117)
                .addGap(68, 68, 68)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(scs124)
                .addGap(18, 18, 18)
                .addComponent(scs125)
                .addGap(18, 18, 18)
                .addComponent(scs126)
                .addGap(18, 18, 18)
                .addComponent(scs127)
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void scs114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scs114ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scs114ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        scsc sc=new scsc();
        int s1=0;
        int s2=0;
        if(scs114.isSelected()){sc.setScs114(1); s1++;}    else{sc.setScs114(0);}
        if(scs115.isSelected()){sc.setScs115(1); s1++;}    else{sc.setScs115(0);}
        if(scs116.isSelected()){sc.setScs116(1); s1++;}    else{sc.setScs116(0);}
        if(scs117.isSelected()){sc.setScs117(1); s1++;}    else{sc.setScs117(0);}
        if(scs124.isSelected()){sc.setScs124(1); s2++;}    else{sc.setScs124(0);}
        if(scs125.isSelected()){sc.setScs125(1); s2++;}    else{sc.setScs125(0);}
        if(scs126.isSelected()){sc.setScs126(1); s2++;}    else{sc.setScs126(0);}
        if(scs127.isSelected()){sc.setScs127(1); s2++;}    else{sc.setScs127(0);}
        
        if(s1>2 && s2>2){
            if(sdb.Enterscs(sc)){
                int op1 =0 ;
                int op2=0;
                int op3=0;
                int op4=0;
                
                String url="jdbc:mysql://localhost:3306/schoolsystem";
                String username="root";
                String password="";
                Connection con= null;
                PreparedStatement pst=null;
                
            try{    
                con=(Connection)DriverManager.getConnection(url,username,password);
                if(scs114.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"scs114");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op1=IndexNum.getInt(1);
                }
               
                  }
                if(scs115.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"scs115");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op2=IndexNum.getInt(1);
                }
               
                  }
                if(scs116.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"scs116");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op3=IndexNum.getInt(1);
                }
               
                  }
                if(scs117.isSelected()){
                
                String query1="SELECT fees FROM subfees WHERE subcode = ?";
                pst= (PreparedStatement)con.prepareStatement(query1);
                pst.setString(1,"scs117");
                IndexNum =pst.executeQuery();
                while (IndexNum.next()) {
                    op4=IndexNum.getInt(1);
                }
               
                  }
            }
                  catch(Exception e){System.out.print(e);
                  }
                JOptionPane.showMessageDialog(this,"Total fee : "+(12000+(op1+op2+op3+op4))); 
            }else{
                JOptionPane.showMessageDialog(this,"failed");}
    }                                        
        else{JOptionPane.showMessageDialog(this,"you have to select more than 2");}  
            
                
                
                
                
                
                
    }//GEN-LAST:event_jButton1ActionPerformed
       

    public int boolToInt(boolean b) {
            return b ? 1 : 0;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox scs114;
    private javax.swing.JCheckBox scs115;
    private javax.swing.JCheckBox scs116;
    private javax.swing.JCheckBox scs117;
    private javax.swing.JCheckBox scs124;
    private javax.swing.JCheckBox scs125;
    private javax.swing.JCheckBox scs126;
    private javax.swing.JCheckBox scs127;
    // End of variables declaration//GEN-END:variables
}
