
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Noob
 */
public class studentEnroll extends javax.swing.JFrame {
    
    studentEnrolldb deb;

    /**
     * Creates new form studentEnroll
     */
    public studentEnroll() {
        this.deb = new studentEnrolldb();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SENnic = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SEname = new javax.swing.JTextField();
        SEnic = new javax.swing.JTextField();
        SEdob = new javax.swing.JTextField();
        SEhometown = new javax.swing.JTextField();
        SEtel = new javax.swing.JTextField();
        course = new javax.swing.JComboBox<>();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        degree = new javax.swing.JComboBox<>();
        SEsubmit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Student Enrollment Form");

        jLabel2.setText("Name :");

        jLabel3.setText("NIC :");

        jLabel4.setText("DOB :");

        jLabel5.setText("Home Town :");

        jLabel6.setText("Tel :");

        SEname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEnameActionPerformed(evt);
            }
        });

        SEnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEnicActionPerformed(evt);
            }
        });

        SEdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEdobActionPerformed(evt);
            }
        });

        SEhometown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEhometownActionPerformed(evt);
            }
        });

        SEtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEtelActionPerformed(evt);
            }
        });

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelor", "Master" }));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });

        male.setText("Male");

        female.setText("Female");

        jLabel7.setText("Gender :");

        jLabel8.setText("Course :");

        jLabel9.setText("Degree :");

        degree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Engineering", "Business" }));

        javax.swing.GroupLayout SENnicLayout = new javax.swing.GroupLayout(SENnic);
        SENnic.setLayout(SENnicLayout);
        SENnicLayout.setHorizontalGroup(
            SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SENnicLayout.createSequentialGroup()
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SENnicLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SENnicLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SEnic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEname, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEdob, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEhometown, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEtel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SENnicLayout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(27, 27, 27)
                        .addComponent(female))
                    .addGroup(SENnicLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
            .addGroup(SENnicLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SENnicLayout.setVerticalGroup(
            SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SENnicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SENnicLayout.createSequentialGroup()
                        .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SEname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(SEnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEhometown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(SENnicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(SENnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 400));

        SEsubmit.setText("SUBMIT");
        SEsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(SEsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    void clearfields(){
        SEname.setText("");
        SEdob.setText("");
        SEnic.setText("");
        SEtel.setText("");
        SEhometown.setText("");


                
    }
    boolean checkdate(String inpt){
       boolean checkFormat;
       
       checkFormat = inpt.matches("([0-9]{4}-[0-9]{2}-[0-9]{2})");
        return checkFormat;
    }
    private void SEsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEsubmitActionPerformed
           //if((SEtel.getText()).length()==10 && (SEnic.getText()).length()==10 && checkdate(SEdob.getText())==true){ 
        
        
        
        
           studentEnrollc ne=new studentEnrollc();
           ne.setName(SEname.getText());
           ne.setDob(SEdob.getText());
           ne.setNic(SEnic.getText());
           ne.setHometown(SEhometown.getText());
           ne.setTel((SEtel.getText()));
           ne.setCourse((String)course.getSelectedItem());
           ne.setDegreetype((String)degree.getSelectedItem());
           if(male.isSelected()){ne.setGender("m");
           
           }if(female.isSelected()){ne.setGender("f");}
           
           
           boolean result=deb.EnrollStd(ne);// passing the created object to studentenrolldb
           if(result=true){
               JOptionPane.showMessageDialog(this, "success");
               
               if(course.getSelectedItem()=="Bachelor"){
                  undergradQual qu= new undergradQual(ne);//passing the created object to undergradQual
                  this.dispose();
                  qu.setVisible(true);
               }
               if(course.getSelectedItem()=="Master"){
                  postgradQual qu= new postgradQual();
                  qu.setVisible(true);
                  if(qu.tf()==true){
                  if(degree.getSelectedItem()=="Computer Science"){}
                  if(degree.getSelectedItem()=="Engineering"){}
                  if(degree.getSelectedItem()=="Business"){}
              }
               }
               //this.dispose();
           }else{
               JOptionPane.showMessageDialog(this, "failed");
           }
           //}else{
               //JOptionPane.showMessageDialog(this, "input error");
               //clearfields();
           //}
    }//GEN-LAST:event_SEsubmitActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void SEtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEtelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEtelActionPerformed

    private void SEnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEnicActionPerformed

    private void SEnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEnameActionPerformed

    private void SEdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEdobActionPerformed

    private void SEhometownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEhometownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEhometownActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentEnroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentEnroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentEnroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentEnroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentEnroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SENnic;
    private javax.swing.JTextField SEdob;
    private javax.swing.JTextField SEhometown;
    private javax.swing.JTextField SEname;
    private javax.swing.JTextField SEnic;
    private javax.swing.JButton SEsubmit;
    private javax.swing.JTextField SEtel;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JComboBox<String> degree;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    // End of variables declaration//GEN-END:variables
}
